# Generated by Django 4.1 on 2022-09-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0002_rename_barangwishlist_attributewatchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributewatchlist',
            name='release_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='attributewatchlist',
            name='watched',
            field=models.CharField(max_length=10),
        ),
    ]
